right_format = """$git_branch"""

[character]
success_symbol = "[➜](bold green)" 
error_symbol = "[■](bold red) "
  
[line_break]
disabled = false

[time]
style="fg:#282c34 bg:#b58900"
format="[▓░$time░▓]($style)"
time_format = "%R"
disabled = true

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "
truncation_length = 3
truncate_to_repo = true
style = "yellow"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "italic purple"
symbol = " "

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
conflicted = "= "
ahead = "⇡×${count} "
behind = "⇣×${count} "
diverged = "${ahead_count}×⇕×${behind_count} "
untracked = "?×${count} "
stashed = "\\$×${count} "
modified = "!×${count} "
staged = "+×${count} "
renamed = "»×${count} "
deleted = "✘×${count} "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[jobs]
symbol = ""

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

